src/Entity/Rejected.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RejectedRepository")
 */
class Rejected
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_product;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rejected_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduct(): ?int
    {
        return $this->id_product;
    }

    public function setIdProduct(int $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getRejectedDate(): ?string
    {
        return $this->rejected_date;
    }

    public function setRejectedDate(string $rejected_date): self
    {
        $this->rejected_date = $rejected_date;

        return $this;
    }
}

src/Controller/ShopsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Product;
use App\Entity\Preferred;
use App\Entity\Rejected;

class ShopsController extends AbstractController
{
    /**
     * @Route("/nearby", name="nearby")
     */
    public function nearby()
    {
    	$session = new Session();
        if ($session->get('name')) {
            $product = $this->getDoctrine()->getRepository(Product::class)->findAll();
            $rejected = $this->getDoctrine()->getRepository(Rejected::class)->findBy(array('id_user' => $session->get('id')));

            return $this->render('shops/nearby.html.twig', array('product' => $product, 'rejected' => $rejected));
        } else {
            return $this->redirectToRoute('signin');
        }   
        
    }

    /**
     * @Route("/sortbydistance", name="sortbydistance", methods={"GET","HEAD","POST"})
     */
    public function sort_by_distance(Request $request)
    {
    	$session = new Session();
        if ($session->get('name')) {
        	$lat = $request->get('lat');
    		$lng = $request->get('lng');
			$product = $this->getDoctrine()->getRepository(Product::class)->findBy(array());
			$nearby = array();
			foreach ($product as $item) {
				
				$distance = pow($item->getLat()-$lat, 2) + pow($item->getLat()+$lat, 2);
				$item->setDistance($distance);
				array_push($nearby, $item);
			}

			foreach ($nearby as $key => $row) {
			    $dist[$key]  = $row->getDistance();
			}

			array_multisort($dist, SORT_DESC, $nearby);

            $rejected = $this->getDoctrine()->getRepository(Rejected::class)->findBy(array('id_user' => $session->get('id')));

            return $this->render('shops/nearby.html.twig', array('product' => $nearby, 'rejected' => $rejected));
        } else {
            return $this->redirectToRoute('signin');
        } 
    }

    /**
     * @Route("/preferred", name="preferred")
     */
    public function preferred()
    {
    	$session = new Session();
        if ($session->get('name')) {
        	// $preferred = new Product();
        	$preferred = array();
        	$idPreferred = array();
            $product = $this->getDoctrine()->getRepository(Preferred::class)->findBy(array('id_user' => $session->get('id')));
            foreach ($product as $item) {

            	array_push($idPreferred, intval($item->getId()));
            	$prod = $this->getDoctrine()->getRepository(Product::class)->findOneBy(['id' => $item->getIdProduct()]);
            	array_push($preferred, $prod);
            }
            return $this->render('shops/preferred.html.twig', array('preferred' => $preferred, 'idPreferred' => $idPreferred ));
        } else {
            return $this->redirectToRoute('signin');
        } 
    }

    /**
     * @Route("/preferred/add/{id}", name="add-preferred")
     */
    public function add_preferred($id)
    {
    $session = new Session();
    if ($session->get('name')) {
        $preferred = new Preferred();
        $id_user = intval($session->get('id'));
        $preferred->setIdUser($id_user);
        $preferred->setIdProduct($id);

        
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($preferred);
        $entityManager->flush();
        return $this->redirectToRoute('preferred');
    
    } else {
            return $this->redirectToRoute('signin');
        }  
    }

    /**
     * @Route("/preferred/remove/{id}", name="delete-preferred")
     */
    public function delete_preferred($id)
    {   
        $session = new Session();
        if ($session->get('name')) {
            $entityManager = $this->getDoctrine()->getManager();
            $preferred = $entityManager->getRepository(Preferred::class)->find($id);
            $entityManager->remove($preferred);
            $entityManager->flush();

            return $this->redirectToRoute('preferred');
        } else {
            return $this->redirectToRoute('signin');
        }   
    }

    /**
     * @Route("/rejected/{id}", name="rejected")
     */
    public function rejected($id)
    {   
        $session = new Session();
        if ($session->get('name')) {
        	$rejected = new Rejected();

        	$now = date("Y-m-d H:i:s");
            $rejectedTime = date('Y-m-d H:i:s',strtotime('+2 hour',strtotime($now)));

            $rejected->setIdProduct($id);
            $rejected->setIdUser($session->get('id'));
            $rejected->setRejectedDate($rejectedTime);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rejected);
            $entityManager->flush();

            return $this->redirectToRoute('nearby');
        } else {
            return $this->redirectToRoute('signin');
        }   
    }
}

templates/shops/nearby.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nearby Shops{% endblock %}

{% block body %}
	<div>
	    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
	        <div class="container"><a href="#" class="navbar-brand" style="font-family:&#39;Allerta Stencil&#39;, sans-serif;"><span class="coding"><em>Coding </em></span><span><em>Challenge</em></span></a><button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
	            <div
	                class="collapse navbar-collapse" id="navcol-1">
	                <ul class="nav navbar-nav ml-auto">
	                    <li class="nav-item"><a href="#" class="nav-link active"><strong>Nearby Shops</strong><br /></a></li>
	                    <li class="nav-item"><a href="{{path('preferred')}}" class="nav-link">My preferred Shops<br /></a></li>
	                    <li class="nav-item"><a href="{{path('logout')}}" class="btn btn-danger">Logout<br /></a></li>
	                </ul>
	        </div>
		</div>
		</nav>
	</div>
    <div>
        <div class="container">
        	<a id = "sortbydistance" href = "#">Sort By Distance</a>
        <form method="post" action="sortbydistance" id="position">
        	<input type="hidden" name="lat" id="lat" value="">
            <input type="hidden" name="lng" id="lng" value="">
        </form>
        	<div class="row">
        		{% set continue = false %}
        		{% for item in product %}

        			{% for val in rejected %}
        				{% if (item.id == val.idProduct) and ("now"|date('d/m/Y H:m:s') < val.rejectedDate|date('d/m/Y H:m:s')) %}
        					{% set continue = true %}
        				{% endif %}
		        			
        			{% endfor %}

        			{% if not continue %}
				        <div class="pt-4 col-md-3 text-center">
			   			 	<span class="head-item">{{item.name}}</span>
			   			 	<img src="{{item.src}}" />
				        	<div class="pt-2 btn-group">
				        		<div class="row text-center">
				        			<div class="col-md-4">
				        				<a class="btn btn-danger" href="/rejected/{{item.id}}">Dislike</a>
				        			</div>

				        			<div class="p-2 l-20 col-md-4">
				        				<span class="head-item">{{item.price}} $</span>
				        			</div>

				        			<div class="col-md-4">
				        				<a class="btn btn-success" href="/preferred/add/{{item.id}}" >Like</a>
				        			</div>
				        		</div>
				        	</div>
					    </div>
				    {% endif %}

				    {% if continue %}
				        {% set continue = false %}
				    {% endif %}

        		{% endfor %}
	   			 
			</div>
		</div>
{% endblock %}

templates/shops/preferred.html.twig
{% extends 'base.html.twig' %}

{% block title %}Preferred Shops{% endblock %}

{% block body %}
	<div>
		<nav class="navbar navbar-light navbar-expand-md navigation-clean">
	    <div class="container"><a href="#" class="navbar-brand" style="font-family:&#39;Allerta Stencil&#39;, sans-serif;"><span class="coding"><em>Coding </em></span><span><em>Challenge</em></span></a><button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
	        <div
	            class="collapse navbar-collapse" id="navcol-1">
	            <ul class="nav navbar-nav ml-auto">
	                <li role="presentation" class="nav-item"><a href="{{path('nearby')}}" class="nav-link">Nearby Shops<br /></a></li>
	                <li role="presentation" class="nav-item"><a href="#" class="nav-link active"><strong>My preferred Shops</strong><br /></a></li>
	                <li class="nav-item"><a href="{{path('logout')}}" class="btn btn-danger">Logout<br /></a></li>
	            </ul>
	    </div>
	    </div>
		</nav>
	</div>
    <div>
        <div class="container">
        	<div class="row">
        		{% set index = 0 %}
	    		{% for item in preferred %}
        			<div class="pt-4 col-md-3 text-center">
		   			 	<span class="head-item">{{item.name}}</span>
		   			 	<img src="{{item.src}}" />
			        	<div class="pt-2 btn-group">
			        		<a class="btn btn-danger" href="/preferred/remove/{{idPreferred[index]}}">Remove</a>
			        	</div>
				    </div>
				    {% set index = index + 1 %}
        		{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}